### ISSUE TITLE
Integrating mangopay into wordpress

### ISSUE THREAD

**Issue by rota90** [aleph1888/mangopay_edd_plugin_web#1]
Hi,
I am novice to wordpress and Mangopay too.
I have to integrate mangopay into a wordpress theme could you please tell me how to proceed, i did not find a good documentation about this.
Thanks in advance

**Comment by rota90** [comment]
when I add the MWPW plugin to my Wordpress theme i got a problem with edd_is_test_mode() undefined method in mwpw_init.php how can I fix this problem?

**Comment by rota90** [comment]
I got that error away by adding easyDigitalDownloads plugin.
Could you please tell me what are the next steps to get Mangopay in my website?

**Comment by rota90** [comment]
I have now this error 'Must configure MangoPay User section in profile.' What does this means??

Where should I configure this??

**Comment by aleph1888** [comment]
Please, follow indications:

https://github.com/aleph1888/mangopay_edd_plugin_web#workflow
